-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE podcast_details (
    id bigint PRIMARY KEY,
    email character varying NOT NULL,
    podcast_url character varying NOT NULL,
    file_id character varying NOT NULL UNIQUE,
    transcription text,
    summary text,
    is_email_sent boolean NOT NULL DEFAULT false,
    state character varying DEFAULT 'IDLE'::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON TABLE podcast_details IS 'This table stores all the details of podcast';

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX podcast_details_file_id_key ON podcast_details(file_id text_ops);
CREATE UNIQUE INDEX podcast_details_pkey ON podcast_details(id int8_ops);
